# Generated by Django 5.1.3 on 2024-11-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0002_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='wealth_status',
            field=models.CharField(
                choices=[('IM', 'Impoverished or in debt'), ('BL', 'On the breadline'), ('FS', 'Financially strained'),
                         ('AV', 'Average'), ('WO', 'Well off'), ('AF', 'Affluent'), ('RI', 'Rich'), ('WE', 'Wealthy')],
                default='AV', max_length=2),
        ),
    ]
