# Generated by Django 5.1.3 on 2024-11-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0003_character_wealth_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.CharField(
                choices=[('GE', 'Generosity'), ('HO', 'Honesty'), ('KI', 'Kindness'), ('LA', 'Laughter'),
                         ('LO', 'Loyalty'), ('MA', 'Magic')], default='MA', max_length=2),
        ),
    ]
