# Generated by Django 5.1.3 on 2024-11-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0005_character_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='movement',
            field=models.CharField(blank=True, choices=[], default='45 ft', max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='origin',
            field=models.CharField(choices=[('P', 'Pegasus'), ('U', 'Unicorn'), ('E', 'Earth Pony')], default='E',
                                   max_length=1),
        ),
    ]
