# Generated by Django 5.1.3 on 2024-11-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0007_remove_character_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='character_images/'),
        ),
    ]
