# Generated by Django 5.1.3 on 2024-11-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0008_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='pronouns',
            field=models.CharField(
                choices=[('SE', 'she/her'), ('HH', 'he/him'), ('TT', 'they/them'), ('SH', 'she/he'), ('ST', 'she/they'),
                         ('HT', 'he/they'), ('AA', 'she/he/they')], default='TT', max_length=2),
        ),
    ]
