# Generated by Django 5.1.3 on 2024-11-13 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0009_character_pronouns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='wealth_status',
        ),
    ]
