# Generated by Django 5.1.3 on 2024-11-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0011_alter_character_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.AddField(
            model_name='character',
            name='special_talent',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
