# Generated by Django 5.1.3 on 2024-11-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0012_delete_useraccount_character_special_talent'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='cm_image',
            field=models.ImageField(blank=True, null=True, upload_to='character_images/'),
        ),
    ]
