# Generated by Django 5.1.3 on 2024-11-19 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0013_character_cm_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='cm_image',
            new_name='cutie_mark_image',
        ),
    ]
