# Generated by Django 5.1.3 on 2024-11-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0015_character_owner_character_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='health',
            field=models.IntegerField(default=0),
        ),
    ]
