# Generated by Django 5.1.3 on 2024-11-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0016_character_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='movement',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
