# Generated by Django 5.1.3 on 2024-11-22 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0017_character_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='smarts',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1),
                                                             django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='character',
            name='social',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1),
                                                             django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1),
                                                             django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1),
                                                             django.core.validators.MaxValueValidator(15)]),
        ),
    ]
