# Generated by Django 5.1.3 on 2024-11-22 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0018_character_smarts_character_social_character_speed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='smarts_status',
            field=models.CharField(blank=True, choices=[('diamond', 'Diamond'), ('gold', 'Gold'), ('silver', 'Silver'),
                                                        ('bronze', 'Bronze')], max_length=10),
        ),
        migrations.AddField(
            model_name='character',
            name='social_status',
            field=models.CharField(blank=True, choices=[('diamond', 'Diamond'), ('gold', 'Gold'), ('silver', 'Silver'),
                                                        ('bronze', 'Bronze')], max_length=10),
        ),
        migrations.AddField(
            model_name='character',
            name='speed_status',
            field=models.CharField(blank=True, choices=[('diamond', 'Diamond'), ('gold', 'Gold'), ('silver', 'Silver'),
                                                        ('bronze', 'Bronze')], max_length=10),
        ),
        migrations.AddField(
            model_name='character',
            name='strength_status',
            field=models.CharField(blank=True, choices=[('diamond', 'Diamond'), ('gold', 'Gold'), ('silver', 'Silver'),
                                                        ('bronze', 'Bronze')], max_length=10),
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('influence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perks',
                                                to='charactercreator.influence')),
            ],
        ),
    ]
