# Generated by Django 5.1.3 on 2024-11-23 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0019_influence_character_smarts_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influence',
            name='hang_up',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BackgroundBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_text', models.CharField(max_length=255)),
                ('influence',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_bonds',
                                   to='charactercreator.influence')),
            ],
        ),
    ]
