# Generated by Django 5.1.3 on 2024-11-23 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0020_influence_hang_up_backgroundbond'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundbond',
            name='bond_text',
        ),
        migrations.RemoveField(
            model_name='influence',
            name='hang_up',
        ),
        migrations.AddField(
            model_name='backgroundbond',
            name='description',
            field=models.TextField(default='fix'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perk',
            name='influence',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='perks',
                                    to='charactercreator.influence'),
        ),
        migrations.CreateModel(
            name='HangUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('influence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hangups',
                                                to='charactercreator.influence')),
            ],
        ),
    ]
