# Generated by Django 5.1.3 on 2024-11-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0021_remove_backgroundbond_bond_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influence',
            name='characteristics',
            field=models.TextField(blank=True),
        ),
    ]
