# Generated by Django 5.1.3 on 2024-11-25 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0022_influence_characteristics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='smarts',
            new_name='base_smarts',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='social',
            new_name='base_social',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='speed',
            new_name='base_speed',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='strength',
            new_name='base_strength',
        ),
    ]
