# Generated by Django 5.1.3 on 2024-11-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0023_rename_smarts_character_base_smarts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='influences',
            field=models.ManyToManyField(blank=True, related_name='characters', to='charactercreator.influence'),
        ),
    ]
