# Generated by Django 5.1.3 on 2024-11-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0024_character_influences'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hang_ups',
            field=models.ManyToManyField(blank=True, related_name='characters', to='charactercreator.hangup'),
        ),
        migrations.AddField(
            model_name='character',
            name='perks',
            field=models.ManyToManyField(blank=True, related_name='characters', to='charactercreator.perk'),
        ),
    ]
