# Generated by Django 5.1.3 on 2024-11-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0025_character_hang_ups_character_perks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='hang_ups',
            field=models.ManyToManyField(blank=True, default=None, related_name='characters',
                                         to='charactercreator.hangup'),
        ),
        migrations.AlterField(
            model_name='character',
            name='influences',
            field=models.ManyToManyField(blank=True, default=None, related_name='characters',
                                         to='charactercreator.influence'),
        ),
        migrations.AlterField(
            model_name='character',
            name='perks',
            field=models.ManyToManyField(blank=True, default=None, related_name='characters',
                                         to='charactercreator.perk'),
        ),
    ]
