# Generated by Django 5.1.3 on 2024-11-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0026_alter_character_hang_ups_alter_character_influences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundbond',
            name='character',
            field=models.ManyToManyField(to='charactercreator.character'),
        ),
        migrations.AddField(
            model_name='hangup',
            name='character',
            field=models.ManyToManyField(to='charactercreator.character'),
        ),
        migrations.AddField(
            model_name='influence',
            name='character',
            field=models.ManyToManyField(to='charactercreator.character'),
        ),
        migrations.AddField(
            model_name='perk',
            name='character',
            field=models.ManyToManyField(to='charactercreator.character'),
        ),
    ]
