# Generated by Django 5.1.3 on 2024-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0027_backgroundbond_character_hangup_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundbond',
            name='character',
        ),
        migrations.RemoveField(
            model_name='hangup',
            name='character',
        ),
        migrations.RemoveField(
            model_name='influence',
            name='character',
        ),
        migrations.RemoveField(
            model_name='perk',
            name='character',
        ),
        migrations.AlterField(
            model_name='character',
            name='hang_ups',
            field=models.ManyToManyField(blank=True, related_name='characters_with_hang_ups',
                                         to='charactercreator.hangup'),
        ),
        migrations.AlterField(
            model_name='character',
            name='influences',
            field=models.ManyToManyField(blank=True, related_name='characters_with_influences',
                                         to='charactercreator.influence'),
        ),
        migrations.AlterField(
            model_name='character',
            name='perks',
            field=models.ManyToManyField(blank=True, related_name='characters_with_perks', to='charactercreator.perk'),
        ),
    ]
