# Generated by Django 5.1.3 on 2024-11-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0028_remove_backgroundbond_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='hang_ups',
        ),
        migrations.AddField(
            model_name='character',
            name='hangups',
            field=models.ManyToManyField(blank=True, related_name='characters', to='charactercreator.hangup'),
        ),
        migrations.AlterField(
            model_name='character',
            name='influences',
            field=models.ManyToManyField(blank=True, related_name='characters', to='charactercreator.influence'),
        ),
        migrations.AlterField(
            model_name='character',
            name='perks',
            field=models.ManyToManyField(blank=True, related_name='characters', to='charactercreator.perk'),
        ),
    ]
