# Generated by Django 5.1.3 on 2024-11-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0029_remove_character_hang_ups_character_hangups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='prerequisite',
            field=models.TextField(blank=True),
        ),
    ]
