# Generated by Django 5.1.3 on 2024-11-27 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0030_perk_prerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='influence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='perks', to='charactercreator.influence'),
        ),
    ]
