# Generated by Django 5.1.3 on 2024-12-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charactercreator', '0031_alter_perk_influence'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='background_bonds',
            field=models.ManyToManyField(blank=True, related_name='characters', to='charactercreator.backgroundbond'),
        ),
    ]
